"""replace_thumbnail_with_cloudinary

Revision ID: 4ed5e9b5f8fd
Revises: f4f83abd26fb
Create Date: 2026-07-15 22:55:21.956308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ed5e9b5f8fd'
down_revision: Union[str, Sequence[str], None] = 'f4f83abd26fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('featured_media', sa.Column('cloudinary_public_id', sa.String(), nullable=True))
    op.drop_column('featured_media', 'thumbnail_url')
    
    # Update seed data
    op.execute(
        "UPDATE featured_media SET "
        "video_url = 'https://res.cloudinary.com/Root/video/upload/quick-strength/reels/90-hold.mp4', "
        "cloudinary_public_id = 'quick-strength/reels/90-hold' "
        "WHERE display_order = 1"
    )
    op.execute(
        "UPDATE featured_media SET "
        "video_url = 'https://res.cloudinary.com/Root/video/upload/quick-strength/reels/handstand.mp4', "
        "cloudinary_public_id = 'quick-strength/reels/handstand' "
        "WHERE display_order = 2"
    )
    op.execute(
        "UPDATE featured_media SET "
        "video_url = 'https://res.cloudinary.com/Root/video/upload/quick-strength/reels/compression-strength.mp4', "
        "cloudinary_public_id = 'quick-strength/reels/compression-strength' "
        "WHERE display_order = 3"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('featured_media', sa.Column('thumbnail_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('featured_media', 'cloudinary_public_id')
    # ### end Alembic commands ###
