"""add_training_level

Revision ID: a08876aafb84
Revises: c6c868746967
Create Date: 2026-07-14 23:11:52.670418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a08876aafb84'
down_revision: Union[str, Sequence[str], None] = 'c6c868746967'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('training_level', sa.Enum('complete_beginner', 'basic_beginner', 'advanced_beginner', 'intermediate', 'advanced', name='traininglevel'), server_default='Complete Beginner', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'training_level')
    # ### end Alembic commands ###
