"""add_featured_media

Revision ID: f4f83abd26fb
Revises: 3c0850dc1da6
Create Date: 2026-07-15 21:50:48.901323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4f83abd26fb'
down_revision: Union[str, Sequence[str], None] = '3c0850dc1da6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    featured_media_table = op.create_table('featured_media',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.Enum('instagram', 'youtube', 'self_hosted', name='platform'), nullable=False),
    sa.Column('media_type', sa.Enum('reel', 'shorts', 'testimonial', name='mediatype'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('caption', sa.String(), nullable=True),
    sa.Column('instagram_url', sa.String(), nullable=True),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('video_url', sa.String(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Seed prototype reels
    import uuid
    from datetime import datetime, UTC
    
    op.bulk_insert(
        featured_media_table,
        [
            {
                'id': uuid.uuid4(),
                'platform': 'instagram',
                'media_type': 'reel',
                'title': 'Muscle Up Progression',
                'caption': 'Master the technique step by step.',
                'instagram_url': 'https://www.instagram.com/reel/DOBEAGaEiWN/',
                'thumbnail_url': None,
                'video_url': None,
                'display_order': 1,
                'is_active': True,
                'created_at': datetime.now(UTC),
                'updated_at': datetime.now(UTC)
            },
            {
                'id': uuid.uuid4(),
                'platform': 'instagram',
                'media_type': 'reel',
                'title': 'Calisthenics Fundamentals',
                'caption': 'Build a solid foundation.',
                'instagram_url': 'https://www.instagram.com/reel/DJMVhcwCJTw/',
                'thumbnail_url': None,
                'video_url': None,
                'display_order': 2,
                'is_active': True,
                'created_at': datetime.now(UTC),
                'updated_at': datetime.now(UTC)
            },
            {
                'id': uuid.uuid4(),
                'platform': 'instagram',
                'media_type': 'reel',
                'title': 'Core Strength Mastery',
                'caption': 'Unlocking advanced movements.',
                'instagram_url': 'https://www.instagram.com/reel/DZ_oo2avEVn/',
                'thumbnail_url': None,
                'video_url': None,
                'display_order': 3,
                'is_active': True,
                'created_at': datetime.now(UTC),
                'updated_at': datetime.now(UTC)
            }
        ]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('featured_media')
    # ### end Alembic commands ###
